// Code generated by "make codegen"; DO NOT EDIT.
package main

type StmtVisitor interface {
	visitExpressionStmt(*Expression) interface{}
	visitPrintStmt(*Print) interface{}
}

type Stmt interface {
	accept(StmtVisitor) interface{}
}

type Expression struct {
	expression Expr
}

func (e *Expression) accept(visitor StmtVisitor) interface{} {
	return visitor.visitExpressionStmt(e)
}

type Print struct {
	expression Expr
}

func (p *Print) accept(visitor StmtVisitor) interface{} {
	return visitor.visitPrintStmt(p)
}
